---
title: "Visualization methods"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualization methods}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Article under development.

This article discusses the methods of visualization of the classification results of workflow described in article `vignette("workflow")`.

# Visualization of the results

TODO: describe all methods 

Each of the $n_i$ indicates a population from the range [0,1] and has an associated group color. Based on that, and the defined exchange classes, for each peptide we construct a color using RGB system. The participation of each group is presented on the chart *x*:

The more red color is selected, the biggest the population of fast-exchanging hydrogens in the peptide.

The more green color is selected, the biggest the population of medium-exchanging hydrogens in the peptide.

The more blue color is selected, the biggest the population of slow-exchanging hydrogens in the peptide.

*Disclaimer: We are aware that the color code convention may lead to inaccessibility for some users with color blindness. We recognize the problem although cannot see the solution without resigning from the RGB color code. For users whom it may concern, we provide numerical data in the web server, next to the plots for direct information.*
